name: flutter_example

authors:
  - vinhngo.share

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_zxing: ^1.0.0
  qr_code_scanner: ^1.0.1
  rxdart: ^0.27.7
  equatable: ^2.0.5
  isar: ^3.0.5

  cupertino_icons: ^1.0.2
  isar_flutter_libs: ^3.0.5
  reorderables: ^0.6.0
  firebase_remote_config: ^4.0.0
  firebase_crashlytics: ^3.1.0
  flutter_barcode_listener: ^0.1.3
  intl: ^0.18.0
  flutter_image_compress: ^2.0.3
  path_provider: ^2.0.15
  flutter_isolate: ^2.0.4
  cached_network_image: ^3.2.3
  storybook_flutter: ^0.12.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: 3.0.5
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  #   - images/a_dot_ham.jpeg

  fonts:
    - family: BlackOpsOne
      fonts:
        - asset: fonts/BlackOpsOne-Regular.ttf
